vim.g.mapleader = " "

require("options")
require("lsp")
require("formatting")
require("colorscheme")
require("netrw")
require("statusline")
require("find")
require("grep")
require("autocommands")
require("diagnostics")
require("keymaps")
require("pairs")
require("terminal")
require("surround")
require("ripgrep")
require("marks")
