return {}
-- return {
-- 	"nvimtools/none-ls.nvim",
--     dependencies = {
--     "nvimtools/none-ls-extras.nvim",
--   },
-- 	config = function()
-- 		local null_ls = require("null-ls")
-- 		null_ls.setup({
-- 			sources = {
-- 				null_ls.builtins.formatting.stylua,
-- 				null_ls.builtins.formatting.prettier,
-- 				null_ls.builtins.completion.spell,
--         require("none-ls.diagnostics.eslint_d"),
--         require("none-ls.code_actions.eslint_d")
-- 			},
-- 			on_attach = function(client, bufnr)
-- 				if client.supports_method("textDocument/formatting") then
-- 					vim.api.nvim_create_autocmd("BufWritePre", {
-- 						group = vim.api.nvim_create_augroup("FormatOnSave", { clear = true }),
-- 						buffer = bufnr,
-- 						callback = function()
-- 							vim.lsp.buf.format({ bufnr = bufnr, async = true })
-- 						end,
-- 					})
-- 				end
-- 			end,
-- 		})
--
-- 		vim.keymap.set("n", "<leader>gf", vim.lsp.buf.format, {})
-- 	end,
-- }
