return {
  -- "rest-nvim/rest.nvim",
  -- dependencies = { "nvim-lua/plenary.nvim" },
  -- config = function()
  --   require("rest-nvim").setup({
  --     result_split_horizontal = false,
  --     result_split_in_place = false,
  --     skip_ssl_verification = true,
  --     encode_url = true,
  --     highlight = {
  --       enabled = true,
  --       timeout = 150,
  --     },
  --     jump_to_request = false,
  --     env_file = ".env",
  --     custom_dynamic_variables = {},
  --     yank_dry_run = true,
  --   })
  --
  --   vim.api.nvim_set_keymap("n", "<leader>rr", "<Plug>RestNvim", { noremap = true, silent = true })
  --   vim.api.nvim_set_keymap("n", "<leader>rp", "<Plug>RestNvimPreview", { noremap = true, silent = true })
  --   vim.api.nvim_set_keymap("n", "<leader>rl", "<Plug>RestNvimLast", { noremap = true, silent = true })
  -- end,
}
